baseURL: https://textbox.clox.nu/
languageCode: en-us
title: textbox.js
theme: 'hugo-book'

publishdir: ../docs

menu:
  after:
    - name: "Playground"
      url: "/playground"
      weight: 10
    - name: "Github"
      url: "https://github.com/cloxnu/textbox.js"
      weight: 20

params:
  BookToC: true
